'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CAJA
    Public Property idCaja As Integer
    Public Property idEstado As Integer
    Public Property nombre As String
    Public Property descripcion As String

    Public Overridable Property ESTADO As ESTADO
    Public Overridable Property CAJA_PRODUCTO As ICollection(Of CAJA_PRODUCTO) = New HashSet(Of CAJA_PRODUCTO)

End Class
