'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CAJA_PRODUCTO
    Public Property idCajaProducto As Integer
    Public Property idProducto As Integer
    Public Property IdCaja As Integer
    Public Property cantidad As Integer

    Public Overridable Property CAJA As CAJA
    Public Overridable Property PRODUCTO As PRODUCTO

End Class
