'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CIUDAD
    Public Property idCiudad As Integer
    Public Property idEstado As Integer
    Public Property idDepartamento As Integer
    Public Property nombre As String

    Public Overridable Property DEPARTAMENTO As DEPARTAMENTO
    Public Overridable Property DEPARTAMENTO1 As DEPARTAMENTO
    Public Overridable Property ESTADO As ESTADO
    Public Overridable Property PEDIDOes As ICollection(Of PEDIDO) = New HashSet(Of PEDIDO)

End Class
