'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DEPARTAMENTO
    Public Property idDepartamento As Integer
    Public Property idEstado As Integer
    Public Property nombre As String

    Public Overridable Property CIUDADs As ICollection(Of CIUDAD) = New HashSet(Of CIUDAD)
    Public Overridable Property CIUDADs1 As ICollection(Of CIUDAD) = New HashSet(Of CIUDAD)
    Public Overridable Property ESTADO As ESTADO

End Class
