'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ESTADO
    Public Property idEstado As Integer
    Public Property nombre As String

    Public Overridable Property CAJAs As ICollection(Of CAJA) = New HashSet(Of CAJA)
    Public Overridable Property CIUDADs As ICollection(Of CIUDAD) = New HashSet(Of CIUDAD)
    Public Overridable Property COMBOes As ICollection(Of COMBO) = New HashSet(Of COMBO)
    Public Overridable Property DEPARTAMENTOes As ICollection(Of DEPARTAMENTO) = New HashSet(Of DEPARTAMENTO)
    Public Overridable Property PEDIDOes As ICollection(Of PEDIDO) = New HashSet(Of PEDIDO)
    Public Overridable Property PEDIDO_PRODUCTO As ICollection(Of PEDIDO_PRODUCTO) = New HashSet(Of PEDIDO_PRODUCTO)
    Public Overridable Property PRODUCTOes As ICollection(Of PRODUCTO) = New HashSet(Of PRODUCTO)
    Public Overridable Property ROLs As ICollection(Of ROL) = New HashSet(Of ROL)
    Public Overridable Property TIPO_PRODUCTO As ICollection(Of TIPO_PRODUCTO) = New HashSet(Of TIPO_PRODUCTO)
    Public Overridable Property USUARIOs As ICollection(Of USUARIO) = New HashSet(Of USUARIO)

End Class
