'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CRACKEDEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CRACKEDEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AUDITORIAs() As DbSet(Of AUDITORIA)
    Public Overridable Property CAJAs() As DbSet(Of CAJA)
    Public Overridable Property CAJA_PRODUCTO() As DbSet(Of CAJA_PRODUCTO)
    Public Overridable Property CIUDADs() As DbSet(Of CIUDAD)
    Public Overridable Property COMBOes() As DbSet(Of COMBO)
    Public Overridable Property COMBO_PRODUCTO() As DbSet(Of COMBO_PRODUCTO)
    Public Overridable Property DEPARTAMENTOes() As DbSet(Of DEPARTAMENTO)
    Public Overridable Property ESTADOes() As DbSet(Of ESTADO)
    Public Overridable Property METODO_PAGO() As DbSet(Of METODO_PAGO)
    Public Overridable Property PEDIDOes() As DbSet(Of PEDIDO)
    Public Overridable Property PEDIDO_PRODUCTO() As DbSet(Of PEDIDO_PRODUCTO)
    Public Overridable Property PRODUCTOes() As DbSet(Of PRODUCTO)
    Public Overridable Property ROLs() As DbSet(Of ROL)
    Public Overridable Property SABORs() As DbSet(Of SABOR)
    Public Overridable Property TIPO_PRODUCTO() As DbSet(Of TIPO_PRODUCTO)
    Public Overridable Property USUARIOs() As DbSet(Of USUARIO)
    Public Overridable Property USUARIO_PRODUCTO() As DbSet(Of USUARIO_PRODUCTO)

End Class
