'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PEDIDO
    Public Property idPedido As Integer
    Public Property idCliente As Integer
    Public Property idDomiciliario As Integer
    Public Property idCiudad As Integer
    Public Property idMetodoPago As Integer
    Public Property idEstado As Integer
    Public Property fechaEntrega As Date
    Public Property fechaVenta As Date
    Public Property direccion As String
    Public Property valor As Double
    Public Property iva As Double

    Public Overridable Property CIUDAD As CIUDAD
    Public Overridable Property ESTADO As ESTADO
    Public Overridable Property METODO_PAGO As METODO_PAGO
    Public Overridable Property PEDIDO_PRODUCTO As ICollection(Of PEDIDO_PRODUCTO) = New HashSet(Of PEDIDO_PRODUCTO)
    Public Overridable Property USUARIO As USUARIO
    Public Overridable Property USUARIO1 As USUARIO

End Class
