'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PEDIDO_PRODUCTO
    Public Property idPedidoProducto As Integer
    Public Property idPedido As Integer
    Public Property Idproducto As Integer
    Public Property IdEstado As Integer
    Public Property IdCliente As Integer
    Public Property cantidad As Integer
    Public Property valorProducto As Double

    Public Overridable Property ESTADO As ESTADO
    Public Overridable Property PEDIDO As PEDIDO
    Public Overridable Property PRODUCTO As PRODUCTO

End Class
