'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PRODUCTO
    Public Property idProducto As Integer
    Public Property idTipoProducto As Integer
    Public Property idEstado As Integer
    Public Property idSabor As Nullable(Of Integer)
    Public Property nombre As String
    Public Property valorUnitario As Double
    Public Property stock As Integer
    Public Property porcion As Integer

    Public Overridable Property CAJA_PRODUCTO As ICollection(Of CAJA_PRODUCTO) = New HashSet(Of CAJA_PRODUCTO)
    Public Overridable Property COMBO_PRODUCTO As ICollection(Of COMBO_PRODUCTO) = New HashSet(Of COMBO_PRODUCTO)
    Public Overridable Property ESTADO As ESTADO
    Public Overridable Property PEDIDO_PRODUCTO As ICollection(Of PEDIDO_PRODUCTO) = New HashSet(Of PEDIDO_PRODUCTO)
    Public Overridable Property SABOR As SABOR
    Public Overridable Property TIPO_PRODUCTO As TIPO_PRODUCTO
    Public Overridable Property USUARIO_PRODUCTO As ICollection(Of USUARIO_PRODUCTO) = New HashSet(Of USUARIO_PRODUCTO)

End Class
