'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TIPO_PRODUCTO
    Public Property idTipoProducto As Integer
    Public Property idEstado As Integer
    Public Property nombre As String

    Public Overridable Property ESTADO As ESTADO
    Public Overridable Property PRODUCTOes As ICollection(Of PRODUCTO) = New HashSet(Of PRODUCTO)

End Class
