'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class USUARIO_PRODUCTO
    Public Property idUsuarioProducto As Integer
    Public Property idUsuario As Integer
    Public Property idProducto As Integer

    Public Overridable Property PRODUCTO As PRODUCTO
    Public Overridable Property USUARIO As USUARIO

End Class
