'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class USUARIO
    Public Property idUsuario As Integer
    Public Property idRol As Integer
    Public Property idEstado As Integer
    Public Property nombre As String
    Public Property apellido As String
    Public Property numeroContacto As String
    Public Property correoElectronico As String
    Public Property contraseña As String

    Public Overridable Property AUDITORIAs As ICollection(Of AUDITORIA) = New HashSet(Of AUDITORIA)
    Public Overridable Property ESTADO As ESTADO
    Public Overridable Property PEDIDOes As ICollection(Of PEDIDO) = New HashSet(Of PEDIDO)
    Public Overridable Property PEDIDOes1 As ICollection(Of PEDIDO) = New HashSet(Of PEDIDO)
    Public Overridable Property ROL As ROL
    Public Overridable Property USUARIO_PRODUCTO As ICollection(Of USUARIO_PRODUCTO) = New HashSet(Of USUARIO_PRODUCTO)

End Class
